runtime: go
api_version: go1.8

handlers:
- url: /swagger-ui/(.*)
  script: _go_app
  secure: always
  login: admin
- url: /api/admin/.*
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app
  secure: always
  login: admin

nobuild_files:
- vendor
- api/swagger-ui

skip_files:
- vendor
